# Write your code here :-)
print('Welcome to the band name generator!')
print('What city did you grow up in?')
city = input()
print('What was the name of your first pet?')
pet = input()
print('Your band name is ' + city + " " + pet + "!")
